version: '3.8'
services:
  nginxplus:
    build: .
    container_name: nginxplus
    restart: always
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./data:/data
      - ./nginx:/etc/nginx